[package]
cairo-version = ">=2.6.3"
name = "metalslug"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && ./scripts/migrate.sh && ./scripts/initialize.sh && ./scripts/grant_auth.sh"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.7.4" }

[[target.dojo]]
